DWAPlannerROS:
  # Velocities
  max_vel_x: 0.5
  min_vel_x: 0.0
  max_vel_trans: 0.5
  min_vel_trans: 0.1
  max_vel_theta: 1.0
  min_vel_theta: 0.4

  # Acceleration
  acc_lim_x: 1.0
  acc_lim_theta: 2.0

  # Goal Tolerance
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false

  # Trajectory Scoring
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01
  forward_point_distance: 0.325
